---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxux
spec:
  replicas: 50
  selector:
    matchLabels:
      app: nginxux
  template:
    metadata:
      labels:
        app: nginxux
    spec:
      containers:
        - name: nginxux
          image: gcr.io/qwiklabs-gcp-01-6e2f0cfefaec/vitcuk:latest
          ports:
            - containerPort: 80
