---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxux
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginxux
  template:
    metadata:
      labels:
        app: nginxux
    spec:
      containers:
        - name: nginxux
          image: nginx:1.14.2
          ports:
            - containerPort: 80
