apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxux
spec:
  replicas: 100
  selector:
    matchLabels:
      app: nginxux
  template:
    metadata:
      labels:
        app: nginxux
    spec:
      containers:
        - name: nginxux
          image: gcr.io/qwiklabs-gcp-04-09e923ce9a47/vitcuk:latest
          ports:
            - containerPort: 80
