apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
    - name: myapp
      image:gcr.io/qwiklabs-gcp-02-dadca81af084/vitcuk:latest
      ports:
        - containerPort: 8080
    - name: envoy
      image: gcr.io/qwiklabs-gcp-02-dadca81af084/vitcuk:latest
